server:
    port: 8002

spring:
    application:
        name: bkex-account
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
#            config:
#                server-addr: 127:0:0:1:8848
management:
    endpoints:
        web:
            exposure:
                include: '*'